version: '3'

services:
  mariadb :
    container_name : mariadb
    build :
      context : ./srcs/requirements/mariadb
      dockerfile : mariadb.Dockerfile
      args:
        - MYSQL_USER_NAME=${MYSQL_USER_NAME}
        - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql:deleguated
    env_file : .env
    restart: always
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    container_name : wordpress
    build :
      context : ./srcs/requirements/wordpress
      dockerfile : wordpress.Dockerfile
    volumes:
      - wordpress-data:/var/www/html:deleguated
    env_file : .env
    restart : on-failure
    networks:
      - inception
  nginx :
    depends_on:
      - wordpress
    container_name: nginx
    build :
      context : srcs/requirements/nginx
      dockerfile : nginx.Dockerfile
    ports :
      - "443:443"
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html:deleguated

volumes :
  mariadb-data:
    driver : local
    driver_opts:
      type: 'none'
      o: 'bind'
      device : '/home/wollio/data'
  wordpress-data:
    driver : local
    driver_opts:
      type: 'none'
      o: 'bind'
      device : '/home/wollio/data'
networks:
  inception:
