version: '3'

services:
  mariadb :
    container_name : mariadb
    build :
      context : ./srcs/requirements/mariadb
      args:
        - MYSQL_USER_NAME=${MYSQL_USER_NAME}
        - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    env_file : .env
    restart: on-failure
    networks:
      - inception
  wordpress:
    container_name : wordpress
    build :
      context : ./srcs/requirements/mariadb
      args:
        - DATABASE_NAME=${DATABASE_NAME}
        - MYSQL_USER_NAME=${MYSQL_USER_NAME}
        - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
        - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME}
        - WORDPRESS_ROOT_PASSWORD=${WORDPRESS_ROOT_PASSWORD}
        - DOMAIN_NAME=${DOMAIN_NAME}
        - BLOG_TITLE=${BLOG_TITLE}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - wordpress-data:/var/www/html
    env_file : .env
    restart : on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    ports :
      - "9000:9000"
  nginx :
    build : srcs/requirements/nginx
    ports :
      - "443:443"
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress-data:/var/www/html

volumes :
  mysql-data:
  wordpress-data:
networks:
  inception:
