version: '3'

services:
  mariadb :
    container_name : mariadb
    build :
      context : ./srcs/requirements/mariadb
      dockerfile : mariadb.Dockerfile
      args:
        - MYSQL_USER_NAME=${MYSQL_USER_NAME}
        - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql:deleguated
    env_file : .env
    restart: on-failure
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    container_name : wordpress
    build :
      context : ./srcs/requirements/wordpress
      dockerfile : wordpress.Dockerfile
      # args:
      #   - DATABASE_NAME=${DATABASE_NAME}
      #   - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      #   - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      #   - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME}
      #   - WORDPRESS_ROOT_PASSWORD=${WORDPRESS_ROOT_PASSWORD}
      #   - DOMAIN_NAME=${DOMAIN_NAME}
      #   - BLOG_TITLE=${BLOG_TITLE}
      #   - ADMIN_EMAIL=${ADMIN_EMAIL}
      #   - DB_HOSTNAME=${DB_HOSTNAME}
    volumes:
      - wordpress-data:/var/www/html:deleguated
    env_file : .env
    restart : on-failure
    networks:
      - inception
  nginx :
    depends_on:
      - mariadb
      - wordpress
    build :
      context : srcs/requirements/nginx
      dockerfile : nginx.Dockerfile
    ports :
      - "443:443"
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html:deleguated

volumes :
  mariadb-data:
  wordpress-data:
networks:
  inception:
